use { value, value-type, error } from types

get-one: function(query: string, returns: value-type) -> expected<value, error>

get-one-with-args: function(query: string, args: list<value>, returns: value-type) -> expected<value, error>
