variant value {
    %string(string),
    %i32(s32),
    %i64(s64),
    %bool(bool),
}

enum value-type {
    %string,
    %i32,
    %i64,
    %bool,
}

variant error {
    %conversion-error(conversion-error),
    %coerce-error(value-type)
}

record conversion-error {
    %value: value,
    %into: value-type,
}