change_in_place: true
excludes:
  - Cargo.toml
  - Cargo.lock
  - rust-toolchain.toml
  - LICENSE
  - ".envrc"
  - ".gitignore"
  - ".dockerignore"
  - "doc/book.toml"
  - "flake\\..*"
  - "logo.*"
  - ".github/**/*"
  - ".cargo/config"
  - "cargo-pgrx/src/templates/*"
  - ".*\\.control"
  - ".*\\.md"
  - ".*\\.nix"
  - ".*\\.yml"
  - ".*\\.png"
licenses:
  - files: any
    ident: PostgreSQL
    authors:
      - name: Technology Concepts & Design, Inc.
        email: opensource@tcdi.com
    template: |
      Portions Copyright 2021-2025 Technology Concepts & Design, Inc.

      All rights reserved.

      Use of this source code is governed by the PostgreSQL license that can be found in the LICENSE file.

comments:
  - columns: 120
    extensions:
      - rs
      - c
      - h
      - sql
    commenter:
      type: block
      start_block_char: "/*\n"
      end_block_char: "\n*/\n"
  - columns: 120
    extension: html
    commenter:
      type: block
      start_block_char: "<!--\n"
      end_block_char: "-->"
  - columns: 80
    extension: any
    commenter:
      type: line
      comment_char: "#"
      trailing_lines: 0
