#! /usr/bin/sh
set -e

(
    if cd postgrestd; then
        git pull
        git submodule update --init --recursive
    else
        git clone https://github.com/workingjubilee/postgrestd.git --recurse-submodules --branch stubout-everything
        cd ./postgrestd
    fi
    mkdir -p $(rustc --print sysroot)/lib/rustlib/x86_64-postgres-linux-gnu/
    cp --verbose --force ./x86_64-postgres-linux-gnu.json $(rustc --print sysroot)/lib/rustlib/x86_64-postgres-linux-gnu/target.json
    cargo clean
    ./build copy
)
PLRUST_TARGET="x86_64-postgres-linux-gnu" cargo test
