#! /usr/bin/sh
set -e

if [ -z "$PLRUST_TARGET" ]; then
    export PLRUST_TARGET="x86_64-unknown-linux-postgres"
fi

(
    if cd postgrestd; then
        git pull
        git submodule update --init --recursive
    else
        git clone https://github.com/workingjubilee/postgrestd.git --recurse-submodules --branch stubout-everything
        cd ./postgrestd
    fi
    cargo clean
    STD_TARGET="$PLRUST_TARGET" ./run install
)

cargo test
