variant value {
    %text(string),
    %text-array(list<option<string>>),
    %int(s32),
    %int-array(list<option<s32>>),
    %bigint(s64),
    %bigint-array(list<option<s64>>),
    %bool(bool),
    %bool-array(list<option<bool>>),
    %bytea(list<u8>),
    %bytea-array(list<option<list<u8>>>),
}

enum value-type {
    %text,
    %text-array,
    %int,
    %int-array,
    %bigint,
    %bigint-array,
    %bool,
    %bool-array,
    %bytea,
    %bytea-array,
}

variant error {
    %conversion-error(conversion-error),
    %coerce-error(value-type),
    %mismatched-arg-length-error(mismatched-arg-length-error),
}

record mismatched-arg-length-error {
    %got: u64,
    %expected: u64,
}

record conversion-error {
    %value: value,
    %into: value-type,
}