variant value {
    %string(string),
    %string-array(list<option<string>>),
    %i32(s32),
    %i32-array(list<option<s32>>),
    %i64(s64),
    %i64-array(list<option<s64>>),
    %bool(bool),
    %bool-array(list<option<bool>>),
}

enum value-type {
    %string,
    %string-array,
    %i32,
    %i32-array,
    %i64,
    %i64-array,
    %bool,
    %bool-array,
}

variant error {
    %conversion-error(conversion-error),
    %coerce-error(value-type),
    %mismatched-arg-length-error(mismatched-arg-length-error),
}

record mismatched-arg-length-error {
    %got: u64,
    %expected: u64,
}

record conversion-error {
    %value: value,
    %into: value-type,
}