/* 
This file is auto generated by pgx.

The ordering of items is not stable, it is driven by a dependency graph.
*/

-- src/lib.rs:73
-- bootstrap

CREATE LANGUAGE plrust
    HANDLER plrust.plrust_call_handler
    VALIDATOR plrust.plrust_validator;
    
COMMENT ON LANGUAGE plrust IS 'PL/rust procedural language';    


-- src/lib.rs:22
-- plrust::plrust_call_handler
CREATE OR REPLACE FUNCTION plrust."plrust_call_handler"() RETURNS trigger
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'plrust_call_handler_wrapper';

-- src/lib.rs:30
-- plrust::plrust_validator
CREATE OR REPLACE FUNCTION plrust."plrust_validator"(
	"fn_oid" Oid /* u32 */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'plrust_validator_wrapper';

-- src/lib.rs:58
-- plrust::recompile_function
CREATE OR REPLACE FUNCTION plrust."recompile_function"(
	"fn_oid" Oid /* u32 */
) RETURNS TABLE (
	"library_path" text,  /* core::option::Option<alloc::string::String> */
	"cargo_output" text  /* alloc::string::String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'recompile_function_wrapper';
